In [27]:
import pandas as pd

#Reading of .csv file
df = pd.read_csv(r"C:\Users\Jurgen\Desktop\FYP\Shared\Tableau Dashboard\Summarised\Tableau_Phase2.csv")


# date = pd.to_datetime(df['Date'])
# print(type(date[0]))

df["Date"] = pd.to_datetime(df["Date"]).dt.strftime('%d/%m/%Y')
df["Date"] = pd.to_datetime(df["Date"])
# df["Date"] = df["Date"].dt.strftime("%m/%d/%Y")
df
# print(date)
# count = 0
# for i in range(len(df)):
#     print(str(df["Date"][i].year) + "/" + str(df["Date"][i].month))

,Date,News_Senti,Volume,Open_USD,Adj_Close_USD,Twitter_Senti,Reddit_Comment,Reddit_SelfText
0,2018-02-07,0.000000,13112253,41.508241,39.984037,0.0000,0.091721,-0.167850
1,2018-03-07,-0.013258,10959655,41.112864,40.782627,0.0000,0.195632,0.065820
2,2018-04-07,0.000000,8776763,41.783077,40.692290,0.0000,0.089100,0.192950
3,2018-05-07,0.000000,7039773,41.233912,40.416246,0.0000,0.107269,0.191075
4,2018-06-07,0.000000,17843706,40.692186,39.487791,0.0000,0.134362,0.167800
...,...,...,...,...,...,...,...,...
318,2019-10-25,0.000000,7879897,43.240752,43.325872,0.3612,0.000000,0.000000
319,2019-10-28,0.107508,6431522,43.335973,43.848824,0.6369,0.000000,0.000000
320,2019-10-29,0.139891,7581629,44.008072,43.751215,0.6729,0.000000,0.000000
321,2019-10-30,0.000000,8959435,43.406557,43.149714,0.9357,0.000000,0.000000
322,2019-10-31,0.107235,10304777,43.661609,43.147943,0.0000,0.000000,0.000000

In [28]:
df.to_csv(r"C:\Users\Jurgen\Desktop\FYP\Shared\Tableau Dashboard\Summarised\Tableau_Phase2.csv", index = False)